In [21]:
import pandas as pd
import numpy as np

## Question 1 Pandas version

In [45]:
pd.__version__

'2.3.2'

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

## Question 2 Records count

In [47]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0       152.0     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [44]:
df.shape

(9704, 11)

## Question 3 Fuel type

In [41]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [6]:
df["fuel_type"].nunique()

2

## Question 4 Missing values

In [46]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Question 5 Max fuel efficiency

In [8]:
max_eficiencia_asia = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

In [9]:
print(max_eficiencia_asia)

23.759122836520497


## Question 6 Median value of horsepower 

In [10]:
median = df["horsepower"].median()
moda = df["horsepower"].mode()[0]

In [11]:
print(median, moda)

149.0 152.0


In [12]:
df['horsepower'] = df["horsepower"].fillna(moda)

In [13]:
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [14]:
print(df["horsepower"].median())

152.0


## Question 7. Sum of weights

In [18]:
cars = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

In [66]:
cars

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [64]:
X_df = cars.head(7)

In [65]:
X_df

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [26]:
X = X_df.values

In [27]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [28]:
XTX = X.T.dot(X)

In [68]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [34]:
XTX_inv = np.linalg.inv(XTX)

In [69]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [33]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [37]:
temp = XTX_inv.dot(X.T)

In [38]:
w = temp.dot(y)

In [70]:
w

array([0.01386421, 0.5049067 ])

In [67]:
sum_w = np.sum(w)

In [71]:
sum_w

np.float64(0.5187709081074016)